server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://@mysql.address@/@mysql.db.name@?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: @mysql.username@
    password: @mysql.password@
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml